name: Build and Push Docker Image

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:latest -f docker/php/Dockerfile .

      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ github.repository }}:latest
